source: "_source"
destination: "_site"
permalink : /willyan/:categories/:title
timezone : America/Sao_Paulo
markdown: kramdown
highlighter : rouge
paginate_path: "/willyan/page:num/"
exclude: ["*.scss", "theme/mohawk/scripts/"]


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "mohawk/blog-detail"
      body__class: "standard"
